apiVersion: v1
kind: ConfigMap
metadata:
  name: mydatabasecm
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mydatabasesecretname
type: Opaque
data:
  postgres-password: bXlwYXNzd29yZA==



