apiVersion: v1
kind: ConfigMap
metadata:
  name: mydatabasecm
data:
  DB_NAME: madatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: mydatabasesecret
type: Opaque
data:
  postgres-password: GlRfptW6DS


